name: auto_authorize_mobile
description: "lohin ECJTU WIFI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  network_info_plus: ^4.1.0+1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: KaiTi
      fonts:
        - asset: fonts\YanZhenQingDuoBaoTaBei.ttf
    
