name: authorize
description: "自动登入ECJTU校园网"
publish_to: 'none'
version: 2.2.4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_local_notifications: ^17.0.0 # 本地通知

  # flutter_native_splash: ^2.4.0 # 闪屏页

  flutter_secure_storage: ^9.0.0 # 本地存储

  http: ^1.2.1 # 网络请求

  network_info_plus: ^4.1.0+1 # 网络状态

  package_info: ^2.0.2 # 包信息

  permission_handler: ^11.3.0 # 权限

  url_launcher: ^6.2.5 # 打开浏览器
  
  workmanager: ^0.5.2 # 后台任务
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: KaiTi
      fonts:
        - asset: fonts/YanZhenQingDuoBaoTaBei.woff
    
# flutter_native_splash:
#   image: images/3.jpg  # 闪屏页的图片路径
#   color: "e4e4e4"  # 闪屏页的背景颜色
#   android: true  # 是否为 Android 平台生成闪屏页
#   ios: false  # 是否为 iOS 平台生成闪屏页
#   web: false  # 是否为 Web 平台生成闪屏页
#   android_gravity: "center"  # Android 平台上图片的位置
